travis:
  secure:
    BINSTAR_TOKEN: ev5wIaNkDwC0KgQRJcE+QuUbLMtKL8vNDqk2kHhJaVfkQ4sFULTrFS0G35tromZjMJ745IBYkj9SysUoanv9EtDMy44m0hdg/EQhb3T0K6ZyRaFd1FiJ+baygDNuBAyceT6KJ41vrAzVmvswP4bJsi0KuPZpVHuleQFyfE9AJmYwT9H4iNp9Ni5N2fN0mQK1qTN1ljQdWFoX6LeT3i5PQZWWt7nbUKxVTkY8lK5RU3uijOFKd2Jq2Z3dsvr3fKmYaW+GUuA1dNAF3gXfOfVitv6CUsxgAIdF1A4VLm2x0v2zAeuZ3NcNliUwfSYJSQ+Yt2x3Jdg3fvI1FW8p1S1tE5fbB6f9gD1Y5AarOJrcDWxwCWL15ycY8nH4Pq0+H/RcqzxrwyglpoQZXkjWMMx2wBToqDtC4KjLP2AR6zNB6Hz5mV+Uk/N+FWuLkmLCSsivSlfV61bwXbWLHNqYbJEkaIgIKZ03zzBZPgfHbIhEjM+cH/xFz8UmsfMbXNlsPs7vz0W8mx8uAiK5eLR+mmKmQr7yovvNYhq4ypvLj624VMnUOg5bIY5F+K1gBfAmxhZovNrV20s4xpPL2MYe1o4SABeygpMi8tts2rZskj/KbfjuyXY9kdgIkBnCqSChkDVuaeyekw0B0zH91tufTUrAq8V81EAaEXRlfVwO8e9pbss=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
