travis:
  secure:
    BINSTAR_TOKEN: SDnYPDU+wRhJ1M8fvDV8pew7oi3xldaMrTIFDqsX4rH7U0aZRddP8QGJfpIdxHEQDHZL+MRlZhTEsHdzHSupf/hLdiqKnuU+KnEDV3NhMGz+hC3nrPLSOWz731zIVWiXsVeGSuyvak/xweQtINZb0G8g7fgylD4MrzqtPAm8jYhgnlVg+/adDrnQ3ammZjg9A2xLXGOH+ySbxhSaobAPz/X3NisB/kvKPGbsuiaoUDDzoe3uhvHZJaqDYz9MHJAKJaTvWSqLc/8ugJDmijqShtLYlVq7PCJq6TNAgLZpnyZn+iZjNGzAbGWuYDJJs80tSyhNbrdW5NyISX4cHSrz1qwO5vlOx78JKeuQzHoqWdOKqCnbnin46iSSVj9YCC8NmOhgDGePu8rmxxJWiQsawv/+mHZCFURgXKguXysBlUeZXs720tsxh8mhJJpy/IAZFPA08hAAt2UOpsSCfFwupv7a/UsgEyv+hXgZCmd/4eroAPdqsZRCGDvXyRukSkzyt7w1WKuVqE27TavPOD5vLR1/QK8ygz/epv1N9erp1tWCW35OUIxcVM16jIjcVDY1E7oGVNSiiOObWfXb6N/xSg30Bn+gVb9acxdJMmCqPdsZ/E0qnxl3x7ypsdWw1xB3+F8AeHGGCUu6o3ocTv8CFummj00/3C4KK1M42oTPdGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
